version: '3.6'
services:
    web:
        build: ./web-service
        restart: always
        volumes:
            - recordings:/mnt/recordings
            - uploads:/mnt/uploads
            - ./web-service/default.conf:/etc/nginx/conf.d/default.conf
            - ./web-service/webroot:/var/www/html
        hostname: stream-webHost
        networks:
            - default
            - dmz_net
        links:
            - php-fpm
    php-fpm:
        build: ./php-fpm
        restart: always
        volumes:
            - recordings:/mnt/recordings
            - uploads:/mnt/uploads
            - ./web-service/webroot:/var/www/html
    db:
        build: ./db-service
        restart: always
        volumes:
            - ./db-service/init:/docker-entrypoint-initdb.d
            - ./db-service/db:/var/lib/mysql
        environment:
            MYSQL_USER: "dbUser"
            MYSQL_PASSWORD: "})U<V-&2X+mg8%~w"
            MYSQL_DATABASE: "mainDB"
            MYSQL_ROOT_PASSWORD: "root-pass"
        expose:
            - "3306"
        hostname: dbHost
        networks:
            - default
    ingest:
        build: ./ingestion-service
        restart: always
        volumes:
            - recordings:/mnt/recordings
        ports:
            - "1935:1935"
        expose:
            - "1935"
        hostname: stream-ingestHost
        networks:
            - default
            - dmz_net
    fileaccess:
        build: ./fileupload-service
        restart: always
        volumes:
            - uploads:/home/admin
        ports:
            - "2221:22"
        networks:
            - default
            - dmz_net
            
volumes:
    recordings:
    uploads:

networks:
    dmz_net:
        external: true
