version: '3'
services:
    web:
        build: ./web-service
        restart: always
        volumes:
            - recordings:/var/www/html/videos
        networks:
            - default
            - dmz_net
    db:
        build: ./db-service
        restart: always
        volumes:
            - ./db-service/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: dbUser
            MYSQL_PASSWORD: db-pass
            MYSQL_DATABASE: testDB
            MYSQL_ROOT_PASSWORD: root-pass
        expose:
            - "3306"
        hostname: dbHost
        networks:
            - default
    ingest:
        image: eledev/stream-ingest:latest
        restart: always
        volumes:
            - recordings:/mnt/recordings
        ports:
            - "1935:1935"
        expose:
            - "1935"
        networks:
            - default
            - dmz_net
    fileaccess:
        build: ./fileupload-service
        restart: always
        volumes:
            - recordings:/home/admin
        ports:
            - "2221:22"
        networks:
            - default
            - dmz_net
            
volumes:
    recordings:

networks:
    dmz_net:
        external: true
